### ISSUE TITLE
Is there a way to make Google Cast replay media continously?

### ISSUE THREAD

**Issue by TriStarGod** [kakone/GoogleCast#11]
Media A - starts
Media A - ends
Media A - starts
... etc

**Comment by kakone** [comment]
Yes, I just added the `QueueLoad `method in the [1.6 version](https://www.nuget.org/packages/GoogleCast/1.6.0) :
```csharp
await mediaChannel.QueueLoadAsync(RepeatMode.RepeatSingle, new Media() { ContentId = "..." });
```
