### ISSUE TITLE
Xamarin Forms

### ISSUE THREAD

**Issue by andersonvieiragomeslopes** [kakone/GoogleCast#12]
Is it possible to use with Xamarin Forms? If yes, how?

**Comment by kakone** [comment]
It's a .Net standard library and you can use it with Xamarin. There is no UI component in this library, what would you like to have exactly ?

**Comment by andersonvieiragomeslopes** [comment]
I have a xamarin forms iptv application, I want to make it possible to play the video to another device (Television) connected in the same network (Wireless ssid or wired), my application uses the standard .Net standard as well.
Sorry if maybe I could not explain you well, I'm from Brazil, my language is different.

**Comment by kakone** [comment]
If your device supports the video format of your iptv channel, it should work.
Use the code in the [README file](https://github.com/kakone/GoogleCast/blob/master/README.md) and replace the ContentId by your video URI to test it.

**Comment by andersonvieiragomeslopes** [comment]
What happens is that I need it to work with android, that has gotten me sleepy.

**Comment by andersonvieiragomeslopes** [comment]
Tutorial: https://github.com/jfversluis/CastRadio
