### ISSUE TITLE
Serialization.InvalidDataContractException for GenericMediaMetadata

### ISSUE THREAD

**Issue by cncb-gh** [kakone/GoogleCast#15]
When I try to call LoadAsync() to play an audio file and try to pass in GenericMediaMetadata the Serialization.InvalidDataContractException is thrown with the message: 
`No set method for property 'MetadataType' in type 'GoogleCast.Models.Media.GenericMediaMetadata'.`

The top of the stack trace is:
`at System.Runtime.Serialization.Json.JsonFormatWriterInterpreter.InternalSerialize(`

**Comment by kakone** [comment]
Fixed in [version 1.6.5](https://www.nuget.org/packages/GoogleCast/1.6.5).
