### ISSUE TITLE
Provide an ID along with FriendlyName?

### ISSUE THREAD

**Issue by nomadyow** [kakone/GoogleCast#19]
I'm using GoogleCast and it works very well!  Thanks for providing this!

My application stores a selected receiver from the list of receivers and casts to that device.  Looking at the exposed attributes of IReceiver I see Friendly Name and IPEndPoint - both of which are dynamic.  IP addresses will change with DHCP and the Friendly Name is alterable by the user.  What I would like to do is store a unique ID for the selected receiver and then use that when it is time to connect.  This way the friendly name can be changed at will without affecting anything.

Is it possible to expose a .Id of somekind against each receiver in IReceiver?

**Comment by nomadyow** [comment]
Thanks for incorporating my PR - any change you could uprev the release on nuget?

**Comment by kakone** [comment]
Available in version [1.6.7](https://www.nuget.org/packages/GoogleCast/1.6.7).

**Comment by kakone** [comment]
Available in version [1.6.7](https://www.nuget.org/packages/GoogleCast/1.6.7).
