### ISSUE TITLE
[Feature] Scan from specific IP address

### ISSUE THREAD

**Issue by Rainmaker52** [kakone/GoogleCast#26]
(Possibly related to #22 )

My desktop has a large number of network interfaces, caused by the Hyper-V role and a large amount of created internal switches.

When scanning for devices using DeviceLocator, it is unable to find any devices. This seems to be due to the fact that the wrong interface is used to scan for devices.

To verify, I tried using SharpCaster. 
I get the same result; no devices found when using the default constructor on DeviceLocator. However, SharpCaster allows me to specify a source IP address in the constructor. When using that specific IP address, my devices _are_ found. Unfortunately, that module is not compatible with .NET Standard.

It would be great if a similar constructor is available in GoogleCast.

**Comment by highwingers** [comment]
did you find any solution to this? i am having same issue. I have multiple VLAN's and GoogleCast cant find Speaks on different Vlan.

**Comment by Rainmaker52** [comment]
Sorry, no. As with too many of my side projects, I abandoned it and just use Android apps instead of my laptop for streaming.

**Comment by kakone** [comment]
Fix available in [1.7.0](https://www.nuget.org/packages/GoogleCast/1.7.0)
